package com.nexusdrive.auth.service.impl;
import com.nexusdrive.auth.dto.*;import com.nexusdrive.auth.entity.*;import com.nexusdrive.auth.repository.*;import com.nexusdrive.auth.service.AuthService;import com.nexusdrive.common.config.JwtProperties;import com.nexusdrive.common.enums.Role;import com.nexusdrive.common.exception.*;import com.nexusdrive.common.security.JwtTokenProvider;import com.nexusdrive.common.util.Sha256HashUtil;import io.jsonwebtoken.JwtException;import java.time.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class AuthServiceImpl implements AuthService {private final UserRepository users;private final RefreshTokenRepository tokens;private final PasswordEncoder encoder;private final JwtTokenProvider jwt;private final JwtProperties props;public AuthServiceImpl(UserRepository u,RefreshTokenRepository t,PasswordEncoder e,JwtTokenProvider j,JwtProperties p){users=u;tokens=t;encoder=e;jwt=j;props=p;}
 public AuthResponse register(RegisterRequest r){if(users.existsByUsernameIgnoreCaseOrEmailIgnoreCase(r.username(),r.email()))throw new ValidationException("Username or email already exists");User u=new User();u.setUsername(r.username().trim());u.setEmail(r.email().trim().toLowerCase());u.setPasswordHash(encoder.encode(r.password()));u.setRole(Role.USER);users.save(u);return issue(u);}
 public AuthResponse login(LoginRequest r){User u=users.findByUsernameIgnoreCase(r.username()).orElseThrow(()->new UnauthorizedException("Invalid credentials"));Instant now=Instant.now();if(u.getLockedUntil()!=null&&u.getLockedUntil().isAfter(now))throw new UnauthorizedException("Account locked until "+u.getLockedUntil());if(!encoder.matches(r.password(),u.getPasswordHash())){int n=u.getFailedLoginAttempts()+1;u.setFailedLoginAttempts(n);if(n>=5){u.setLockedUntil(now.plus(Duration.ofMinutes(15)));u.setFailedLoginAttempts(0);}users.save(u);throw new UnauthorizedException("Invalid credentials");}u.setFailedLoginAttempts(0);u.setLockedUntil(null);users.save(u);return issue(u);}
 public AuthResponse refresh(String raw){var rt=findValid(raw);try{if(!"refresh".equals(jwt.parse(raw).get("type",String.class)))throw new UnauthorizedException("Invalid refresh token");}catch(JwtException e){throw new UnauthorizedException("Invalid refresh token");}rt.setRevoked(true);tokens.save(rt);return issue(rt.getUser());}
 public void revoke(String raw){tokens.findByTokenHash(Sha256HashUtil.hash(raw.getBytes())).ifPresent(t->{t.setRevoked(true);tokens.save(t);});}
 private RefreshToken findValid(String raw){RefreshToken t=tokens.findByTokenHash(Sha256HashUtil.hash(raw.getBytes())).orElseThrow(()->new UnauthorizedException("Invalid refresh token"));if(t.isRevoked()||t.getExpiresAt().isBefore(Instant.now()))throw new UnauthorizedException("Expired or revoked refresh token");return t;}
 private AuthResponse issue(User u){String a=jwt.generateAccessToken(u.getId(),u.getUsername(),u.getRole().name()),r=jwt.generateRefreshToken(u.getId(),u.getUsername(),u.getRole().name());RefreshToken t=new RefreshToken();t.setUser(u);t.setTokenHash(Sha256HashUtil.hash(r.getBytes()));t.setExpiresAt(Instant.now().plusMillis(props.getRefreshExpirationMs()));tokens.save(t);return new AuthResponse(a,r,jwt.accessExpirationSeconds());}}
